import PageContent from "../../components/pageContent";
import Head from "next/head";

export default function Environmental() {
  const heading = "Environmental Finance";

  return (
    <>
      <Head>
        <title>Environmental Finance | Structured Captital Solutions</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageContent heading={heading} />
    </>
  );
}
