import PageContent from "../../components/pageContent"
import Services from '../../components/servicesList'
import Head from 'next/head'

export default function About () { 
    const heading= "Services"
    const paragraphs=[
        "Structured Capital Solutions prides itself on its innovative product range and focuses on the development of market leading structured finance strategies. These strategies encompass various topical domestic and cross-border financing elements.",
        "Indicative transaction sizes usually range from $250 million to over $2 billion, but could be less than $100m.",
        "SCS also joint ventures with other firms and has in-house legal expertise with respect to tax and regulatory capital concerns."
    ]
    return ( 
        <>
            <Head>
                <title>Services | Structured Captital Solutions</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <PageContent heading={heading} paragraphs={paragraphs}/>
            <Services/>
        </>
    )
}