import { adam } from "../../data/partners";
import Profile from "../../components/profile";
import Head from "next/head"

export default function Adam() {
  return (
    <>
      <Head>
        <title>Adam Parr | Structured Captital Solutions</title>
        <meta name="description" content="Generated by create next app" />
      </Head>{" "}
      <Profile {...adam} />
    </>
  );
}
