import PageContent from "../../components/pageContent"
import PartnersLink from "../../components/partnersLink"
import { partners } from '../../data/partners'
import Head from 'next/head'

export default function About () { 

    const heading="Senior Partners"
    const paragraphs=[
        "Structured Capital Solutions brings together a team of experienced professionals with the senior partners all having over 17 years of experience in these markets.",
        "The senior partners all have significant track records with major international banks and investment banks prior to forming SCS."
    ]

    return ( 
        <>
            <Head>
                <title>Senior Partners | Structured Captital Solutions</title>
                <meta name="description" content="Generated by create next app" />
            </Head>
            <PageContent heading={heading}>
                <p>{paragraphs[0]}</p>
                <p>{paragraphs[1]}</p>
                {partners.map((item, i) => {
                    return <PartnersLink key={item.name} { ...item }/>
                })}
            </PageContent>
        </>
    )
}