import { marc } from "../../data/partners";
import Profile from "../../components/profile";
import Head from "next/head";

export default function Adam() {
  return (
    <>
      <Head>
        <title>Mar Fuhrman | Structured Captital Solutions</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Profile {...marc} />{" "}
    </>
  );
}
