import { paul } from "../../data/partners";
import Profile from "../../components/profile";
import Head from "next/head";

export default function Paul() {
  return (
    <>
      <Head>
        <title>Paul Edwards | Structured Captital Solutions</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <Profile {...paul} />
    </>
  );
}
