import PageContent from "../components/pageContent";
import Head from "next/head";

export default function About() {
  const heading = "What We Do";
  const paragraphs = [
    "Structured Capital Solutions and its team have been retained advisors to various major financial institutions, fortune 500 companies, hedge funds and private equity funds. SCS originates and markets sophisticated products, and acts as an advisor to implement such proposed strategies. Such implementation may include sourcing of counterparties, raising or investment of funds and provision of strategic advice that ranges from evaluation of appropriate strategy to full execution of the final transaction.",
    "The transactions themselves generally involve an enhancement through accounting or tax efficiencies, such as availing of government incentives including, but not limited to, tax credits and exempt income regimes. Additionally, some transactions enhance value through timing differences or more efficient “character” (i.e., “ordinary” vs. “capital” or vice versa).",
    "SCS has broad connectivity within the finance sector in North America, the United Kingdom, Europe and Asia and has the expertise and experience to advise on and execute large scale complex financing and investment transactions.",
  ];

  return (
    <>
      <Head>
        <title>What we do | Structured Captital Solutions</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <PageContent heading={heading} paragraphs={paragraphs} />
    </>
  );
}
