import Head from "next/head";

export default function About() {
  const heading = "Contact Us";

  return (
    <>
      <Head>
        <title>Contact Us | Structured Captital Solutions</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <div className="content">
        <h1 className="page-title">Contact Us</h1>
        <p>
          Any questions relating to the contents herein should be directed to{" "}
          <a href="paul.html">Paul Edwards</a> or{" "}
          <a href="adam.html">Adam Parr</a> of SCS:
        </p>
      </div>
    </>
  );
}
